export const stateData = [
  {
    date: 1665360000000,
    totalIntern: 0,
    totalExtern: 0,
    productTypesData: [
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  },
  {
    date: 1665446400000,
    totalIntern: 0,
    totalExtern: 0,
    productTypesData: [
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  },
  {
    date: 1665532800000,
    totalIntern: 3,
    totalExtern: 0,
    productTypesData: [
      {
        intern: 1,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 1,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 1,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 1,
        extern: 0,
        internProd: 280,
        externProd: 0,
        sectionCapacity: null,
        total: 1,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 1,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 1,
        sumGesters: 560
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 1,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 1,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 1,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  },
  {
    date: 1665619200000,
    totalIntern: 0,
    totalExtern: 3,
    productTypesData: [
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 1,
        internProd: 0,
        externProd: 100,
        sectionCapacity: null,
        total: 1,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 2,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 2,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  },
  {
    date: 1665705600000,
    totalIntern: 1,
    totalExtern: 0,
    productTypesData: [
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 1,
        extern: 0,
        internProd: 120,
        externProd: 0,
        sectionCapacity: null,
        total: 1,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 1,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 1,
        sumGesters: 240
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  },
  {
    date: 1665792000000,
    totalIntern: 1,
    totalExtern: 0,
    productTypesData: [
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 1,
        extern: 0,
        internProd: 600,
        externProd: 0,
        sectionCapacity: null,
        total: 1,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 1,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 1,
        sumGesters: 1200
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  },
  {
    date: 1665878400000,
    totalIntern: 0,
    totalExtern: 0,
    productTypesData: [
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Entrée",
        key: "STARTER",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Plat",
        key: "MAIN_COURSE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Meal Prep",
        key: "MEAL_PREP",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Yaourt",
        key: "YAOURT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Dessert",
        key: "DESSERT",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Pain",
        key: "BREAD",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      },
      {
        intern: 0,
        extern: 0,
        internProd: 0,
        externProd: 0,
        sectionCapacity: null,
        total: 0,
        expectedSale: 0,
        label: "Fromage",
        key: "CHEESE",
        difficulty1: 0,
        difficulty2: 0,
        difficulty3: 0,
        averageDifficulty: 0,
        sumGesters: 0
      }
    ]
  }
];
